name: CI-Pipeline

on : 
  # workflow_dispatch:  
  push

jobs:
  sentilytics-sentiment-testing:
    runs-on: "ubuntu-latest"

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.4"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.11.6

      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      
      - name: install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          uv sync --extra test

      - name: run dvc pipeline
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          uv run dvc repro 
      
      - name: run model tests
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run : |
          uv run pytest
